version: '3.8'

services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - balance_postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d # для файла SQL
    environment:
      POSTGRES_DB: balance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "54322:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  balanceapp:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c '/wait-for-it.sh db:5432 -- gunicorn avito_tech_balance.wsgi --bind unix:/gunicorn_socket/gunicorn_socket.sock'
#      sh -c '/wait-for-it.sh db:5432 -- gunicorn avito_tech_balance.wsgi --bind 0.0.0.0:8000'
#      sh -c '/wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8080'
    expose:
      - 8000
    volumes:
      - static_volume:/balanceapp/static
      - gunicorn_socket:/gunicorn_socket
    environment:
      - DATABASE_NAME=balance_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - default

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/balanceapp/static
      - gunicorn_socket:/gunicorn_socket
    depends_on:
      - balanceapp

networks:
  default:
    driver: bridge

volumes:
  balance_postgres_data:
  static_volume:
  gunicorn_socket:


