version: '3.8'

services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - balance_postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d # для файла SQL
    environment:
      POSTGRES_DB: balance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "54322:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  balanceapp:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c '/wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8080'
    ports:
      - "8000:8080"
    environment:
      - DATABASE_NAME=balance_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - default

  test:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c '/wait-for-it.sh db:5432 -- python manage.py test'
    environment:
      - DATABASE_NAME=balance_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  balance_postgres_data:
    external: true

# docker volume create balance_postgres_data
# docker-compose up -d


